### ISSUE TITLE
error: cannot find symbol

### ISSUE THREAD

**Issue by parthbhatti** [MostafaAnter/VideoPlayerInsideRecyclerView#2]
import com.parthbhatti.dubdub.databinding.TiktokTimelineItemRecyclerBindingImpl;
                                         ^
  symbol:   class TiktokTimelineItemRecyclerBindingImpl
  location: package com.parthbhatti.dubdub.databinding

**Comment by MostafaAnter** [comment]
@parthbhatti clean project then rebuild it then it will work
