### ISSUE TITLE
Deleting item but next item not starts playing automatically

### ISSUE THREAD

**Issue by AndroidDeveloperMCT** [MostafaAnter/VideoPlayerInsideRecyclerView#5]
When I remove any item from the recycler view, the next items come on the above position but not starts playing automatically.

Can anyone please help me out

**Comment by MostafaAnter** [comment]
You need to call playIndexThenPause Previous Player method after execute deletion ![Screenshot_20210223_140436.jpg](https://user-images.githubusercontent.com/9489649/108841299-39eeaf80-75e0-11eb-8f80-095d7dce2468.jpg)

**Comment by mf-mindcrewtech** [comment]
I am calling this

                ```
modelList.removeAt(position)
                notifyItemRemoved(position)
                notifyItemRangeChanged(position, maroofmodelList.size)
                
               if (index != -1) {
                    PlayerViewAdapter.playIndexThenPausePreviousPlayer(index)
                }
```
                
                But still not working

**Comment by AndroidDeveloperMCT** [comment]
I am calling this

modelList.removeAt(position)
notifyItemRemoved(position)
notifyItemRangeChanged(position, modelList.size)
if (index != -1) {
                    PlayerViewAdapter.playIndexThenPausePreviousPlayer(index)
                }
                

but still not working

Any idea, what I am doing wrong? Please let me know

**Comment by MostafaAnter** [comment]
Try to remove item without notify item changes just remove item from model list and set viability of view holder that u want to delete to gone although call method of playing next item

**Comment by AndroidDeveloperMCT** [comment]
modelList.remove(model)
binding.root.setVisibility = View.GONE
if (index != -1) {
PlayerViewAdapter.playIndexThenPausePreviousPlayer(index)
}

Tried above but still, the video does not start playing automatically

* I need to scroll down to the next video to get the video player started working.

**Comment by MostafaAnter** [comment]
Great next step is scroll to position programically with animation it should work

**Comment by MostafaAnter** [comment]
Your problem depends on your code logic not belon the concept of implementing Exoplayer inside recyclerview

**Comment by AndroidDeveloperMCT** [comment]
I don't think so it is because of code logic because I am running demo only and added the delete button at top/right.

It would be helpful to me if you please add some code for delete in TikTok screen and share the branch PLEASE

**Comment by MostafaAnter** [comment]
Email me if you would like to hire me for this task, have a great day buddy

**Comment by AndroidDeveloperMCT** [comment]
Anyway thanks
